<?xml version="1.0" encoding="utf-8"?><Database Name="GymManagement" Class="MainDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2SM595H\SQLEXPRESS;Initial Catalog=GymManagement;Integrated Security=True" SettingsObjectName="Gym_management_appication.Properties.Settings" SettingsPropertyName="GymManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="ma" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gioiTinh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="soDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ngayThamGia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="ID" Type="System.String" DbType="NChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Luong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>